# Your GitHub workflow file under .github/workflows/
on:
  push:
    branches:
      - main
    
jobs:
  generate_and_publish_docs:
    runs-on: ubuntu-latest
    name: Generate and publish the docs
    steps:
    - uses: actions/checkout@v1
      name: Checkout code
    - uses: nunit/docfx-action@v2.4.0
      name: Build Documentation
      with:
        args: docfx_project/docfx.json
    - uses: maxheld83/ghpages@master
      name: Publish Documentation on GitHub Pages
      env:
        BUILD_DIR: docfx_project/_site # docfx's default output directory is _site
        GH_PAT: ${{ secrets.GH_PAT }} # See https://github.com/maxheld83/ghpages
